language: node_js
node_js:
  - "5.2.0"
before_script:
  - sudo apt-get install python
  - sudo apt-get install python-pip
  - sudo -H pip install numpy
  - npm install -g elm elm-test
  - elm-package install -y
script:
    - cd tests
    - make test
